- frontend/.gitignore
Close #8 
ex) feature/fe/gitignore/-> develop
- production 폴더
- dependencies 폴더
- env 파일
- log 파일
- misc
ignore 추가
Co-authored-by: Jeongmin Woo <greenblues1190@gmail.com>
> [FE] .gitignore 작성

- frontend/.eslintrc.js
- frontend/.storybook/preview.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/DiscussionItem/index.tsx
- frontend/src/hooks/useFetch.ts
- frontend/src/index.tsx
- frontend/src/mocks/browser.ts
- frontend/src/mocks/fixtures/Discussions.ts
- frontend/src/mocks/handlers.ts
- frontend/src/mocks/handlers/discussionHandlers.ts
- frontend/src/mocks/handlers/index.ts
- frontend/src/pages/DiscussionDetailPage/index.tsx
- frontend/src/pages/DiscussionListPage/index.tsx
- frontend/src/pages/DiscussionPostPage/index.tsx
- frontend/src/types/DiscussionTypes.ts
- frontend/tsconfig.json
Close #24 #26 
feature/fe/api-mocking -> develop
- API Mocking
- MSW 환경설정
- POST /discussions
- GET /discussions
- GET /discussions/{discussionId}
- 기능 연결 및 테스트
- API Mocking 구현
- 기능 연결 및 테스트 완료
> [FE] API Mocking 및 연결, 테스트

- frontend/src/components/@shared/Input/Input.stories.jsx
- frontend/src/components/@shared/Input/Input.styled.ts
- frontend/src/components/@shared/Input/index.tsx
- frontend/src/components/@shared/TextArea/TextArea.stories.jsx
- frontend/src/components/@shared/TextArea/TextArea.styled.ts
- frontend/src/components/@shared/TextArea/index.tsx
- frontend/src/components/OpinionItem/OpinionItem.stories.jsx
- frontend/src/components/OpinionItem/OpinionItem.styled.ts
- frontend/src/components/OpinionItem/index.tsx
- frontend/src/pages/DiscussionDetailPage/DiscussionDetailPage.styled.ts
- frontend/src/pages/DiscussionDetailPage/index.tsx
- frontend/src/pages/DiscussionPostPage/DiscussionPostPage.styled.ts
- frontend/src/pages/DiscussionPostPage/index.tsx
- frontend/src/types/OpinionTypes.ts
Close #33 
feature/fe/opinion-ui -> develop
-  DiscussionDetailPage Opinion Section
-  OpinionItem
-  Input
-  TextArea
컴포넌트 구현 및 적용
> [FE] Opinion UI 구현

- frontend/src/pages/MeetingPage/MeetingPage.stories.jsx
- frontend/src/pages/MeetingPage/MeetingPage.styled.ts
- frontend/src/pages/MeetingPage/index.tsx
Close #43 
feature/fe/meeting-ui
MeetingPage 컴포넌트 구현
> [FE] 출결 체크 페이지 UI 구현

- frontend/src/hooks/useFetch.ts
- frontend/src/mocks/fixtures/meeting.ts
- frontend/src/mocks/fixtures/users.ts
- frontend/src/mocks/handlers/index.ts
- frontend/src/mocks/handlers/meetingHandler.ts
- frontend/src/mocks/handlers/userHandler.ts
- frontend/src/pages/MeetingPage/index.tsx
Close #50 
feature/fe/meeting-api -> dev
- 유저 리스트, 출결 정보 API Mocking
- 기능 연결 및 테스트
- API Mocking
- MeetingPage에 API 연결 및 테스트
> [FE] 출결 체크 페이지 기능 구현

- frontend/src/pages/MeetingPage/index.tsx
Close #55 
feature/fe/modal-window
모달 메시지 수정
모달 메시지 수정
> [FE] Modal 메시지 수정

- backend/src/main/java/com/woowacourse/moragora/controller/MeetingController.java
- backend/src/main/java/com/woowacourse/moragora/dto/MeetingRequest.java
- backend/src/main/java/com/woowacourse/moragora/repository/MeetingRepository.java
- backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
- backend/src/test/java/com/woowacourse/moragora/acceptance/AcceptanceTest.java
- backend/src/test/java/com/woowacourse/moragora/acceptance/MeetingAcceptanceTest.java
- backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
- backend/src/test/java/com/woowacourse/moragora/repository/MeetingRepositoryTest.java
- backend/src/test/java/com/woowacourse/moragora/service/MeetingServiceTest.java
close #62 
feature/be/meeting-post -> dev
- Meeting 생성 기능
> [BE] Meeting 생성 기능 추가 및 테스트

- frontend/src/components/@shared/RadioButton/index.tsx
- frontend/src/hooks/useForm.ts
- frontend/src/pages/MeetingPage/index.tsx
feature/fe/hooks -> dev
폼 상태관리 훅 분리
useForm 구현
> [FE] useForm 훅 분리

- backend/src/main/java/com/woowacourse/moragora/controller/ControllerAdvice.java
- backend/src/main/java/com/woowacourse/moragora/dto/ErrorResponse.java
- backend/src/main/java/com/woowacourse/moragora/dto/MeetingRequest.java
- backend/src/main/java/com/woowacourse/moragora/entity/Meeting.java
- backend/src/main/java/com/woowacourse/moragora/exception/MeetingNotFoundException.java
- backend/src/main/java/com/woowacourse/moragora/exception/meeting/IllegalStartEndDateException.java
- backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
- backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
- backend/src/test/java/com/woowacourse/moragora/entity/MeetingTest.java
Close #77 
feat/be/meeting-validation -> dev
- 필수 입력값이 하나라도 없는 경우 (400)
- 종료 날짜가 시작 날짜보다 이른 경우 (400)
- 모임의 길이가 50자를 초과하는 경우 (400)
> [BE] Meeting 생성 요청에 대한 예외 핸들링

- backend/src/main/java/com/woowacourse/moragora/MoragoraApplication.java
- backend/src/main/java/com/woowacourse/moragora/dto/MeetingRequest.java
- backend/src/main/java/com/woowacourse/moragora/dto/MeetingResponse.java
- backend/src/main/java/com/woowacourse/moragora/dto/UserResponse.java
- backend/src/main/java/com/woowacourse/moragora/repository/UserRepository.java
- backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
- backend/src/test/java/com/woowacourse/moragora/acceptance/MeetingAcceptanceTest.java
- backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
- backend/src/test/java/com/woowacourse/moragora/repository/UserRepositoryTest.java
- backend/src/test/java/com/woowacourse/moragora/service/MeetingServiceTest.java
close #72 
feature/be/meeting-add-attendance -> dev
Meeting 생성 시에 User 목록으로 Attendance를 추가한다.
> [BE] Meeting 생성 시에 User 목록으로 Attendance 생성

- frontend/src/hooks/useForm.ts
- frontend/src/mocks/fixtures/meeting.ts
- frontend/src/mocks/fixtures/users.ts
- frontend/src/mocks/handlers/meetingHandler.ts
- frontend/src/mocks/handlers/userHandler.ts
- frontend/src/pages/LoginPage/index.tsx
- frontend/src/pages/RegisterPage/index.tsx
Close #93 #94 
feature/fe/api-mocking -> dev
- 로그인, 회원가입 API mocking, 기능 연결
- 이메일 중복 확인 API mocking, 기능 연결
api 추가, 기능 연결
> [FE] 로그인, 회원 가입, 이메일 중복 확인 API mocking 및 기능 연결

- frontend/.storybook/main.js
- frontend/.storybook/preview.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.stories.jsx
- frontend/src/App.tsx
- frontend/src/components/layouts/Header/index.tsx
- frontend/src/index.tsx
- frontend/src/mocks/fixtures/meeting.ts
- frontend/src/mocks/handlers/meetingHandler.ts
- frontend/src/pages/LoginPage/LoginPage.styled.ts
- frontend/src/pages/LoginPage/index.tsx
- frontend/src/pages/MeetingListPage/MeetingListPage.styled.ts
- frontend/src/pages/MeetingListPage/index.tsx
- frontend/src/pages/MeetingPage/MeetingPage.stories.jsx
- frontend/src/pages/MeetingPage/index.tsx
- frontend/src/pages/RegisterPage/index.tsx
- frontend/src/router/index.tsx
- frontend/webpack.config.js
Close #39 
feature/fe/router-setting -> dev
- `react-router-dom` 설치 및 라우터 적용
- 비동기 로직에 라우팅 추가
- 스토리북 react-router-v6 addon 추가
- 비동기 로직에 라우팅 추가
- BrowserRouter, GlobalStyles, ThemProvider App파일에서 index파일로 이동
> [FE] 라우팅 구현 및 스토리북 설정 추가

- frontend/src/pages/MeetingPage/MeetingPage.stories.jsx
Close #106 
feature/fe/fix-meeting-page-story -> dev
MeetingPage 스토리 에러 수정
MeetingPage 스토리에서 withRouter 데코레이터와 parameter 프로퍼티 이름 수정
> [FE] MeetingPage 스토리 라우터 설정 수정

- frontend/src/components/@shared/InputHint/InputHint.stories.jsx
- frontend/src/components/@shared/InputHint/InputHint.styled.ts
- frontend/src/components/@shared/InputHint/index.tsx
- frontend/src/components/CoffeeStackItem/CoffeeStackItem.stories.jsx
- frontend/src/components/CoffeeStackItem/CoffeeStackItem.styled.ts
- frontend/src/components/CoffeeStackItem/index.tsx
- frontend/src/components/MeetingItem/MeetingItem.stories.jsx
- frontend/src/components/MeetingItem/MeetingItem.styled.ts
- frontend/src/components/MeetingItem/index.tsx
- frontend/src/components/UserItem/UserItem.stories.jsx
- frontend/src/components/UserItem/UserItem.styled.ts
- frontend/src/components/UserItem/index.tsx
- frontend/src/pages/LoginPage/LoginPage.styled.ts
- frontend/src/pages/LoginPage/index.tsx
- frontend/src/pages/MeetingCreatePage/MeetingCreatePage.styled.ts
- frontend/src/pages/MeetingCreatePage/index.tsx
- frontend/src/pages/MeetingListPage/MeetingListPage.styled.ts
- frontend/src/pages/MeetingListPage/index.tsx
- frontend/src/pages/MeetingPage/MeetingPage.styled.ts
- frontend/src/pages/MeetingPage/index.tsx
- frontend/src/pages/RegisterPage/RegisterPage.styled.ts
- frontend/src/pages/RegisterPage/index.tsx
Close #115 
feature/fe/component-seperate -> dev
- 컴포넌트 분리
- 컴포넌트 분리
- MeetingItem
- UserItem
- InputHint
- css prop들 styled 파일로 분리
- 스토리북 추가
> [FE] 컴포넌트 및 스타일 분리

- frontend/.babelrc
- frontend/.storybook/.babelrc
- frontend/.storybook/main.js
- frontend/package-lock.json
- frontend/package.json
- frontend/public/index.html
- frontend/tsconfig.json
- frontend/webpack.config.js
- frontend/webpack/webpack.common.js
- frontend/webpack/webpack.dev.js
- frontend/webpack/webpack.prod.js
Close #125 #100 #57 
feature/fe/build-env -> dev
- 웹팩 config 설정
- 빌드 환경 별 config 설정 분리
- ts에서 바벨로 로더 변경
- 스토리북 빌드 환경 설정
- 절대 경로 사용 위해 웹팩 `TsconfigPathsPlugin` 설정
- classic jsx 런타임에서 동작하도록 바벨 config 추가
- 절대 경로 문제 해결
- React is not defined 문제 해결
- `.babelrc`에서 `@emotion/babel-preset-css-prop` 제거, `@emotion/babel-preset-css-prop`는 new jsx runtime에서 동작하지 않음
추후 번들링 최적화에 대한 논의가 필요합니다.
> [FE] 빌드 환경 설정

- frontend/src/mocks/handlers/meetingHandler.ts
- frontend/src/pages/MeetingCreatePage/MeetingCreatePage.styled.ts
- frontend/src/pages/MeetingCreatePage/index.tsx
- frontend/src/types/meetingType.ts
- frontend/src/utils/timeUtil.ts
Close #119 
feature/fe/meeting-create-api -> dev
- 모임 생성 api mocking
- MeetingCreatePage에 post 및 성공 시 네비게이션 로직 추가
> [FE] 모임 생성 API 모킹 및 기능 연결

- backend/build.gradle
- backend/src/docs/asciidoc/auth.asciidoc
- backend/src/docs/asciidoc/index.asciidoc
- backend/src/docs/asciidoc/meeting.asciidoc
- backend/src/docs/asciidoc/user.asciidoc
- backend/src/main/java/com/woowacourse/auth/config/AuthWebConfig.java
- backend/src/main/java/com/woowacourse/moragora/dto/MyMeetingResponse.java
- backend/src/main/java/com/woowacourse/moragora/dto/MyMeetingsResponse.java
- backend/src/test/java/com/woowacourse/auth/controller/AuthControllerTest.java
- backend/src/test/java/com/woowacourse/moragora/controller/ControllerTest.java
- backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
- backend/src/test/java/com/woowacourse/moragora/controller/UserControllerTest.java
Close #176 
feat/be/rest-docs -> dev
- WebMvcTest에 Rest docs 적용하기
- asciidoc으로 문서화하기
> [BE] REST Docs 적용하기

- frontend/src/components/MeetingItem/MeetingItem.styled.ts
- frontend/src/components/MeetingItem/index.tsx
- frontend/src/hooks/useTimer.ts
- frontend/src/mocks/fixtures/meeting.ts
- frontend/src/mocks/handlers/meetingHandler.ts
- frontend/src/pages/MeetingListPage/index.tsx
- frontend/src/types/meetingType.ts
feature/fe/update-api -> dev
- serverTIme 타입 변경
- active에서 isActive로 이름 변경
- 서버 시각 기준으로 초마다 렌더링
> [FE] 유저별 참여 모임 전체 조회 API 변경 반영

- frontend/src/pages/MeetingListPage/MeetingListPage.styled.ts
- frontend/src/pages/MeetingListPage/index.tsx
Close #187 
feature/fe/bug-fix -> dev
p 태그 내부에 div 선언 에러 수정
스켈레톤 ui를 div에서 p 요소로 수정하고 스타일 설정
> [FE] p 태그 내부에 div 선언 에러 수정

- backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
Close #184 
feature/be/meeting-findById-refactor -> dev
- findById() 리팩터링
- getTardyCount() 네이밍 변경
> [BE] Meeting 관련 메서드 리팩토링

- backend/src/main/java/com/woowacourse/auth/config/AuthWebConfig.java
Close #152 
feature/be/cors-handling -> dev
- Cross-origin 문제 해결
> [BE] cross-origin 허용

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/UserItem/index.tsx
- frontend/src/hooks/useFetch.ts
- frontend/src/hooks/useQuerySelectItems.ts
- frontend/src/mocks/handlers/meetingHandler.ts
- frontend/src/mocks/handlers/userHandler.ts
- frontend/src/pages/LoginPage/index.tsx
- frontend/src/pages/MeetingCreatePage/index.tsx
- frontend/src/pages/RegisterPage/index.tsx
- frontend/webpack/webpack.common.js
Close #173
feature/fe/config-env -> dev
dotenv 설치 및 웹팩 설정
QA 후 staging env, production env 설정 필요
> [FE] 개발 env 서버 url 설정

- frontend/src/pages/RegisterPage/index.tsx
Close #191 
feature/fe/bug-fix -> dev
회원가입 닉네임 인풋 유효성 검사 로직 수정
회원가입 닉네임 인풋 pattern 수정
> [FE] 회원가입 폼 nickname 인풋 pattern 수정

- backend/src/main/java/com/woowacourse/moragora/dto/UserRequest.java
- backend/src/main/java/com/woowacourse/moragora/entity/user/RawPassword.java
- backend/src/test/java/com/woowacourse/moragora/controller/UserControllerTest.java
- backend/src/test/java/com/woowacourse/moragora/entity/user/RawPasswordTest.java
Close #195 
feature/be/password-fix-regex -> dev
- 비밀번호 검증 시 대문자도 통과
- 대문자 허용 검증을 위한 몇 가지 test case가 추가되었습니다.
> [BE] 비밀번호 검증 시 대문자 허용

- frontend/src/hooks/useTimer.ts
- frontend/src/pages/MeetingListPage/index.tsx
- frontend/src/pages/RegisterPage/index.tsx
feature/fe/fix-timer-rigister-form -> dev
> [FE] 타이머, 회원가입 버그 수정 및 자동 refetching

- frontend/src/pages/RegisterPage/index.tsx
feature/fe/fix-regex -> dev
버그 픽스
닉네임 인풋 정규표현식 앞 소괄호 추가
> [FE] 닉네임 정규표현식 수정

- frontend/src/pages/MeetingListPage/index.tsx
feature/fe/fix-page -> dev
테스트 용 시간 표시를 제거한다.
MeetingListPage에서 테스트 용 시간 표시를 제거했습니다.
> [FE] 테스트 용 시간 표시 제거

- backend/src/main/java/com/woowacourse/ApplicationStartupRunner.java
- backend/src/main/java/com/woowacourse/auth/service/AuthService.java
- backend/src/main/java/com/woowacourse/moragora/repository/attendance/AttendanceHibernateRepository.java
- backend/src/main/java/com/woowacourse/moragora/repository/attendance/AttendanceRepository.java
- backend/src/main/java/com/woowacourse/moragora/repository/attendance/AttendanceSpringJpaRepository.java
- backend/src/main/java/com/woowacourse/moragora/repository/meeting/MeetingHibernateRepository.java
- backend/src/main/java/com/woowacourse/moragora/repository/meeting/MeetingRepository.java
- backend/src/main/java/com/woowacourse/moragora/repository/meeting/MeetingSpringJpaRepository.java
- backend/src/main/java/com/woowacourse/moragora/repository/participant/ParticipantHibernateRepository.java
- backend/src/main/java/com/woowacourse/moragora/repository/participant/ParticipantRepository.java
- backend/src/main/java/com/woowacourse/moragora/repository/participant/ParticipantSpringJpaRepository.java
- backend/src/main/java/com/woowacourse/moragora/repository/user/UserHibernateRepository.java
- backend/src/main/java/com/woowacourse/moragora/repository/user/UserRepository.java
- backend/src/main/java/com/woowacourse/moragora/repository/user/UserSpringJpaRepository.java
- backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
- backend/src/main/java/com/woowacourse/moragora/service/UserService.java
- backend/src/test/java/com/woowacourse/moragora/repository/AttendanceHibernateRepositoryTest.java
- backend/src/test/java/com/woowacourse/moragora/repository/MeetingHibernateRepositoryTest.java
- backend/src/test/java/com/woowacourse/moragora/repository/ParticipantHibernateRepositoryTest.java
- backend/src/test/java/com/woowacourse/moragora/repository/UserHibernateRepositoryTest.java
Close #212 
feature/be/data-jpa -> dev
- 기존의 Hibernate를 SpringData JPA로 이전
현재 UserRepository의 findByNicknameContainingOrEmailContaining 메서드가 @Query없이는 작동하지 않습니다. 아무래도 Or 때문인거 같은데 혹시 해결책을 아시는 분 있으면 코멘트 부탁드립니다!
> [BE] SpringData JPA로 이전

- frontend/src/hooks/useTimer.ts
- frontend/src/pages/MeetingListPage/index.tsx
Close #218 
feature/fe/timer-refactoring -> dev
- parameter로 전달받은 interval간격으로 시간을 업데이트한다.
- `useTimer`훅에  `intervalMs` 인자 추가
-  경과된 ms시간 간격이 `intervalMs`보다 크거나 같을 경우 `elapsed` 업데이트
> [FE] Timer 훅 리펙토링

- frontend/src/utils/request.ts
Close #224 
feature/fe/usefetch-refactoring -> dev
`utils/request.ts` 추가
> [FE] useFetch 리팩토링

- frontend/src/mocks/handlers/commonHandler.ts
- frontend/src/mocks/handlers/meetingHandler.ts
- frontend/src/types/meetingType.ts
Close #229 
feature/fe/api-mocking -> dev
- 모임 변경 API 반영
- 커피스택 비우기 mock API 추가
> [FE] 추가, 수정된 API 모킹

- .gitmodules
- backend/build.gradle
- backend/src/main/java/com/woowacourse/moragora/controller/UserControllerAspect.java
- backend/src/main/resources/application.yml
> [TEST] sub-module and DB connection

- .gitmodules
> [TEST] submodule test

- backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
Close #252 
feature/be/find-meeting-by-user -> dev
MeetingAttendances 생성 시 잘못된 참가자 수가 들어가던 버그를 수정한다.
> [BE] MeetingAttendances 생성 시 잘못된 참가자 수가 들어가던 버그 수정

- frontend/src/mocks/handlers/meetingHandler.ts
- frontend/src/pages/MeetingPage/index.tsx
- frontend/src/types/meetingType.ts
Close #258 
feature/fe/meeting-api-isactive -> dev
> [FE] 모임 단일 조회 변경 API 반영

- backend/build.gradle
- backend/src/main/java/com/woowacourse/auth/dto/LoginRequest.java
- backend/src/main/java/com/woowacourse/auth/dto/LoginResponse.java
- backend/src/main/java/com/woowacourse/logging/LoggingAspect.java
- backend/src/main/java/com/woowacourse/moragora/controller/ControllerAdvice.java
- backend/src/main/java/com/woowacourse/moragora/dto/EmailCheckResponse.java
- backend/src/main/java/com/woowacourse/moragora/dto/ErrorResponse.java
- backend/src/main/java/com/woowacourse/moragora/dto/MeetingRequest.java
- backend/src/main/java/com/woowacourse/moragora/dto/MeetingResponse.java
- backend/src/main/java/com/woowacourse/moragora/dto/MyMeetingResponse.java
- backend/src/main/java/com/woowacourse/moragora/dto/MyMeetingsResponse.java
- backend/src/main/java/com/woowacourse/moragora/dto/ParticipantResponse.java
- backend/src/main/java/com/woowacourse/moragora/dto/UserAttendanceRequest.java
- backend/src/main/java/com/woowacourse/moragora/dto/UserRequest.java
- backend/src/main/java/com/woowacourse/moragora/dto/UserResponse.java
- backend/src/main/java/com/woowacourse/moragora/dto/UsersResponse.java
- backend/src/main/resources/file-error-appender.xml
- backend/src/main/resources/file-info-appender.xml
- backend/src/main/resources/file-warn-appender.xml
- backend/src/main/resources/logback-spring.xml
feature/be/logging -> dev
- log를 파일로 남기기
노션에 정리해서 올리겠습니다!!
> [BE] Logging 처리

- frontend/src/components/@shared/Calendar/DateCell/index.tsx
feature/fe/calendar-allow -> dev
> [FE] 일정 생성 시 현재 날짜 선택 허용

- backend/src/main/java/com/woowacourse/moragora/dto/MeetingResponse.java
- backend/src/main/java/com/woowacourse/moragora/entity/MeetingAttendances.java
- backend/src/main/java/com/woowacourse/moragora/service/AttendanceService.java
- backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
- backend/src/test/java/com/woowacourse/moragora/acceptance/AttendanceAcceptanceTest.java
- backend/src/test/java/com/woowacourse/moragora/entity/MeetingAttendancesTest.java
Close #272
feature/be/coffee-time -> dev
- 오늘 출석 마감 전까지는 오늘의 출석은 반영하지 않게 한다.
> [BE] isCoffeeTime 관련 로직 분기처리

- frontend/.gitignore
- frontend/cypress.config.ts
- frontend/cypress/e2e/app.cy.ts
- frontend/cypress/support/component-index.html
- frontend/cypress/support/component.ts
- frontend/cypress/tsconfig.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/mocks/configs/index.ts
- frontend/src/pages/MeetingCreatePage/MeetingCreatePage.styled.ts
- frontend/src/pages/MeetingCreatePage/index.tsx
- frontend/tsconfig.json
- frontend/webpack/webpack.test.js
Close #259 
feature/fe/e2e-test -> dev
> [FE] E2E 테스트 코드 작성

- frontend/webpack/webpack.common.js
Close #206  
feature/fe/history-api-fallback -> dev
- webpack config에 publicPath 추가
> [FE] Nginx history API fallback 설정

- frontend/cypress/e2e/app.cy.ts
- frontend/src/apis/userApis.ts
- frontend/src/components/UserItem/index.tsx
- frontend/src/mocks/configs/index.ts
Close #279 
feature/fe/fix-typo -> dev
출결 요청의 페이로드 attendanceStatus의 오타 수정.
> [FE] 출결 요청 시 서버에서 에러 발생 픽스

- backend/src/main/java/com/woowacourse/moragora/dto/UserAttendanceRequest.java
Close #277
feature/be/status-validate -> dev
- 잘못된 필드로 요청이 올 경우 에러 응답
> [BE] 출석체크 요청에 대한 검증 추가

- backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
- backend/src/main/java/com/woowacourse/moragora/dto/UserAttendanceRequest.java
- backend/src/main/java/com/woowacourse/moragora/exception/meeting/NotCheckInTimeException.java
- backend/src/main/java/com/woowacourse/moragora/service/AttendanceService.java
- backend/src/test/java/com/woowacourse/moragora/acceptance/AttendanceAcceptanceTest.java
- backend/src/test/java/com/woowacourse/moragora/controller/AttendanceControllerTest.java
- backend/src/test/java/com/woowacourse/moragora/service/AttendanceServiceTest.java
Close #296 
feature/be/attendance-submit -> dev
- 출석 제출 요청 필드 변경
Acceptance test는 일단 주석으로 그대로 뒀어요..! Attendance 초기화 로직이 바뀌고 나서 작성할 수 있을 듯 합니다 😢
> [BE] 출석 제출 API 수정

- frontend/src/mocks/fixtures/meetings_new.ts
- frontend/src/mocks/handlers/meetingHandler_new.ts
- frontend/src/mocks/handlers/userHandler.ts
- frontend/src/types/meetingType_new.ts
- frontend/src/types/userType_new.ts
Close #323 
feature/fe/update-api-> dev
- 추가된 API 모킹 핸들러 추가
- 해당 API 요청, 응답 타입 추가
> [FE] 8월 11일 수정, 추가된 API 모킹

- frontend/.storybook/.babelrc
Close #325 
feature/fe/fix-storybook-emotion-styled-error -> dev
스토리북에서 emotion styled의 컴포넌트 셀렉터 사용 시 에러 발생 픽스
스토리북에서 emotion styled의 컴포넌트 셀렉터 사용 시 에러 발생하여 스토리북 babel 설정에 emotion 플러그인 추가했습니다. 자세한 내용은 이슈를 참고하세요. #325
> [FE] 스토리북에서 emotion Component selector 사용 시 에러 픽스

- frontend/.storybook/.babelrc
Close #325 
feature/fe/fix-storybook-emotion-styled-error -> dev
storybook babelrc emotion 플러그인 앞에 @을 추가
storybook babelrc emotion 플러그인 앞에 @을 추가
> [FE] storybook babelrc emotion plugin 앞에 @ 추가

- frontend/src/components/@shared/Calendar/AdvancedConfiguration/index.tsx
- frontend/src/hooks/useForm.ts
- frontend/src/pages/EventCreatePage/index.tsx
- frontend/src/pages/LoginPage/index.tsx
- frontend/src/pages/MeetingCreatePage/index.tsx
- frontend/src/pages/RegisterPage/index.tsx
Close #205 
feature/fe/refactor-useform -> dev
- 이벤트 핸들러에서 target 대신 currentTarget 사용하도록 변경
- 유효성 검사 후 input에 `valid`, `invalid` 클래스 추가
- 폼 제출 시 invalid 값이 있는 첫번째 input 자동 포커스
- `customValidations` : 사용자 커스텀 제약과 커스텀 에러 메시지 옵션 추가
- `patternValidationMessage` : 패턴 검사 커스텀 에러 메시지 옵션 추가
- `watch` :  선택하여 인풋 값을 `values` 상태에 업데이트하는 옵션 추가
> [FE] 폼 훅 리팩토링

- backend/src/main/java/com/woowacourse/auth/config/AuthWebConfig.java
- backend/src/test/java/com/woowacourse/moragora/controller/AttendanceControllerTest.java
- backend/src/test/java/com/woowacourse/moragora/controller/UserControllerTest.java
Close #328 
hotfix/0.1.1 -> main
- 로그인을 하지 않고 로그인이 필요한 기능 요청 시 Status code 401 return
- 모든 요청에 대해 LoginInterceptor 적용
- UnAuthorized status Test case 추가
> [BE] 요청에 대해 LoginInterceptor 적용, 테스트 추가 및 hotfix

- frontend/src/hooks/useMutation.ts
- frontend/src/hooks/useQuery.ts
- frontend/src/utils/request.ts
Close #357 
feature/fe/fix-request -> dev
> [FE] request 반환값 수정

- .gitmodules
- backend/.gitignore
- backend/build.gradle
- backend/src/main/resources/application.yml
Close #341
feature/be/submodule-init -> dev
- 백엔드용 서브모듈을 등록합니다.
- 아래의 접속이 가능해야 합니다.
- 로컬- h2
- 개발 - MySQL
- 운영 - MySQL (인텔리제이에서는 X)
최상단에서 `git add ` 를 적용시 backend / frontend 에서 하던 것과는 다르게 적용이 됩니다 :)
> [ALL] 서브모듈 초기화 설정

- .github/workflows/sonarqube.yml
Close #380 
feature/be/sonarqube-with-submodule-> dev
- 소나큐브에서 서브모듈 내부 파일을 읽을 수 있게 한다.
> [BE] 소나큐브 서브모듈 적용

- .github/workflows/sonarqube.yml
Close #386 
feature/be/sonarqube-with-submodule -> dev
소나큐브 workflow에서 서브모듈 토큰을 읽어온다.
> [BE] 소나큐브 서브모듈 토큰 에러

- frontend/src/consts/index.ts
- frontend/src/hooks/useQuery.ts
- frontend/src/types/queryType.ts
feature/fe/fix-get-user-data-query -> dev
> [FE] query status에 idle 추가

- frontend/src/apis/eventApis.ts
- frontend/src/mocks/handlers/eventHandler.ts
- frontend/src/pages/CalendarPage/index.tsx
- frontend/src/pages/LoginPage/index.tsx
- frontend/src/pages/MeetingCreatePage/index.tsx
Close #391 
feature/fe/fix-calendar-page -> dev
- 시작 시간 설정 시 마감 시간 활성화
> [FE] 일정 설정 페이지 input disabled 수정

- frontend/src/components/GoogleLoginButton/GoogleLoginButton.styled.ts
- frontend/src/components/GoogleLoginButton/index.tsx
Close #393 
feature/fe/login-button-fix -> dev
- height 및 배경 수정
> [FE] 구글 로그인 버튼 스타일 수정

- frontend/src/apis/eventApis.ts
- frontend/src/apis/meetingApis.ts
- frontend/src/mocks/handlers/eventHandler.ts
- frontend/src/mocks/handlers/meetingHandler.ts
- frontend/src/pages/CalendarPage/index.tsx
- frontend/src/pages/MeetingConfigPage/index.tsx
- frontend/src/pages/UnregisterPage/index.tsx
- frontend/src/types/eventType.ts
Close #397 
feature/fe/fix-master-api-url -> dev
- 마스터 넘기기 api url 변경
- `/meetings/:meetingId/me` -> `/meetings/:meetingId/master`로 변경
- 이벤트 삭제 버튼에 api 요청 매핑
- 회원탈퇴 확인 메시지를 로그인한 유저의 이메일로 보여주기
- 모임 나가기 api url 변경
> [FE] 버그 수정

- frontend/src/components/@shared/Calendar/index.tsx
- frontend/src/contexts/calendarContext.tsx
- frontend/src/pages/CalendarPage/index.tsx
Close #404 
feature/fe/calendar -> dev
- 서버에 저장된 일정도 날짜 호버 시 하이라이트 되도록 수정
> [FE] 캘린더 페이지 버그 수정

- frontend/src/pages/CheckInPage/index.tsx
- frontend/src/pages/MeetingDetailPage/index.tsx
Close #406 
feature/fe/check-page-fix -> dev
- 에러페이지 조건 수정
> [FE] 출석부 에러 페이지 버그 수정

- frontend/src/pages/CheckInPage/index.tsx
feature/fe/fix-checkin-page -> dev
- 참여 중인 모임이 있으면 empty state ui를 보여주지 않도록 수정
> [FE] 출결 페이지 버그 수정

- frontend/src/pages/CheckInPage/AttendanceSection/AttendanceSection.styled.ts
- frontend/src/pages/CheckInPage/AttendanceSection/index.tsx
- frontend/src/pages/CheckInPage/index.tsx
feature/fe/fix-check-page -> dev
- 출석부 버그 수정
> [FE] 출석부 페이지 버그 수정

- backend/build.gradle
Close #442 
feature/be/configure-prometheus -> dev
- Spring boot Application의 상태를 동적으로 제공하는 Spring Boot Actuator 의존성 추가
> [BE] Prometheus 관련 의존성 추가

- backend/src/main/java/com/woowacourse/logging/LoggingFilter.java
- backend/src/main/java/com/woowacourse/logging/QueryCountInspector.java
- backend/src/main/java/com/woowacourse/moragora/config/HibernateConfig.java
- backend/src/test/java/com/woowacourse/logging/QueryCountInspectorTest.java
- backend/src/test/java/com/woowacourse/moragora/acceptance/CommonAcceptanceTest.java
- backend/src/test/java/com/woowacourse/moragora/acceptance/MeetingAcceptanceTest.java
- backend/src/test/java/com/woowacourse/moragora/application/auth/AuthServiceTest.java
- backend/src/test/java/com/woowacourse/moragora/domain/event/EventRepositoryTest.java
- backend/src/test/java/com/woowacourse/moragora/domain/event/EventsTest.java
- backend/src/test/java/com/woowacourse/moragora/domain/participant/ParticipantTest.java
- backend/src/test/java/com/woowacourse/moragora/domain/user/password/EncodedPasswordTest.java
- backend/src/test/java/com/woowacourse/moragora/presentation/CommonControllerTest.java
- backend/src/test/java/com/woowacourse/moragora/presentation/ControllerTest.java
- backend/src/test/java/com/woowacourse/moragora/presentation/UserControllerTest.java
Close #439 
feature/be/logging-query-count -> dev
> [BE] Request 마다 query count를 로깅하는 기능

- frontend/src/components/CheckMeetingItem/CheckMeetingItem.styled.ts
Close #454 
feature/fe/fix-CheckMeetingItem-style -> dev
- cursor point
- background-color 설정
> [FE] CheckIn Page의 MeetingItem Hover 스타일 추가

- .github/workflows/frontend-ci.yml
- frontend/.babelrc
- frontend/cypress/e2e/app.cy.ts
- frontend/cypress/fixtures/example.json
Closes #471 
feature/fe/add-github-actions-workflow -> dev
- 워크플로우 yaml 파일을 추가한다.
- 워크플로우 yaml 파일 추가
- 테스트 코드 성공하도록 수정
> [FE] Github Actions 프론트엔드 CI 워크플로우 추가

- backend/src/main/resources/application.yml
Close #473 
feature/be/configure-tomcat -> dev
- tomcat thread pool 관련 설정
- hikari connection pool을 함께 조정하여 DB connection 부족으로 인한 부하를 완화했습니다.
> [BE] tomcat thread pool, hikari connection pool 설정

- backend/src/main/java/com/woowacourse/moragora/support/SchedulerStartUp.java
Close #481 
feature/be/login -> dev
> [BE] Scheduler에서 request scope인 빈을 참조하는 버그 수정

- backend/src/main/java/com/woowacourse/moragora/presentation/auth/LoginInterceptor.java
Close #486 
hotfix/1.1.2 -> dev
만료된 토큰에 대한 응답을 500에서 401로 수정한다
> [BE] LoginInterceptor annotation 검사 로직 오류 수정

- backend/src/main/java/com/woowacourse/moragora/domain/attendance/Attendance.java
- backend/src/main/java/com/woowacourse/moragora/domain/event/Event.java
- backend/src/main/java/com/woowacourse/moragora/domain/meeting/Meeting.java
- backend/src/main/java/com/woowacourse/moragora/domain/participant/Participant.java
feature/be/entity -> dev
- ManyToOne에 대한 FetchType Lazy로 설정
- OneToMany에 대한 명시적인 FetchType 선언 제거
> [BE] ManyToOne FetchType Lazy로 일괄 수정

- backend/build.gradle
- backend/src/main/java/com/woowacourse/moragora/presentation/StatusCheckController.java
- backend/src/test/java/com/woowacourse/moragora/application/auth/RefreshTokenProviderTest.java
Close #530 
feature/be/simple-check-scheduler-> dev
- 현재 기동한 서버가 스케쥴러인지 아닌지를 나타내는 API를 작성합니다.
- `/check/is-scheduler`
- StatusCheckController 를 추가합니다.
> [BE] 배포한 서버가 스케쥴러인지를 나타내는 API 개발

- backend/build.gradle
- backend/src/main/java/com/woowacourse/moragora/application/auth/RefreshTokenProvider.java
- backend/src/main/java/com/woowacourse/moragora/config/RedisConfig.java
- backend/src/main/java/com/woowacourse/moragora/domain/auth/RefreshToken.java
- backend/src/main/java/com/woowacourse/moragora/domain/auth/RefreshTokenRepository.java
- backend/src/test/java/com/woowacourse/moragora/config/EmbeddedRedisConfig.java
- backend/src/test/java/com/woowacourse/moragora/domain/auth/RefreshTokenRepositoryTest.java
Closes #535 
feature/be/refresh-token-redis -> dev
- Refresh token 관리를 Redis로 이전한다.
> [BE] Refresh Token 관리 Redis로 이전

- frontend/src/pages/CheckInPage/AttendanceSection/index.tsx
Close #553 
feature/fe/fix-attendances-query -> dev
- AttendanceSection의 쿼리 키를 수정한다.
- 쿼리 키에 meeting id 추가
> [FE] Attendances 쿼리 키 수정

- backend/src/main/java/com/woowacourse/moragora/application/MeetingService.java
- backend/src/main/java/com/woowacourse/moragora/domain/geolocation/BeaconRepository.java
- backend/src/test/java/com/woowacourse/moragora/acceptance/AcceptanceTest.java
- backend/src/test/java/com/woowacourse/moragora/acceptance/MeetingAcceptanceTest.java
- backend/src/test/java/com/woowacourse/moragora/application/MeetingServiceTest.java
Close #555
feature/be/fix-delete-meeting -> dev
- 미팅 삭제 시 비콘 테이블 함께 삭제
> [BE] 모임 삭제 요청 시 Beacon 테이블 함께 삭제

- backend/src/main/resources/application.yml
Close #560 
feature/be/config-hikari-cp -> dev
- [성능 테스트](https://brazen-serpent-b4f.notion.site/for-Hikari-CP-ebcc578a520a4df6b829fc6400e2109d)를 통해 적절한 hikari cp max값 설정
> [BE] hikari connection pool 설정

- frontend/src/apis/userApis.ts
- frontend/src/pages/RegisterPage/RegisterPage.styled.ts
Close #563 
- [] 기능 추가
feature/fe/login-bug-fix
> [FE] 로그인 credential 설정 및 회원가입 인증하기 버튼 안보이는 버그 수정

- frontend/emotion.d.ts
- frontend/src/components/@shared/Calendar/Calendar.styled.ts
- frontend/src/components/@shared/Calendar/DateCell/DateCell.styled.ts
- frontend/src/components/@shared/Calendar/MonthControlBox/MonthControlBox.styled.ts
- frontend/src/components/@shared/Calendar/MonthControlBox/index.tsx
- frontend/src/components/@shared/Calendar/WeekCell/WeekCell.styled.ts
- frontend/src/components/@shared/Calendar/index.tsx
- frontend/src/components/@shared/TimePicker/TimePicker.stories.jsx
- frontend/src/components/@shared/TimePicker/TimePicker.styled.ts
- frontend/src/components/@shared/TimePicker/index.tsx
- frontend/src/contexts/calendarContext.tsx
- frontend/src/pages/CalendarPage/CalendarPage.styled.ts
- frontend/src/pages/CalendarPage/index.tsx
- frontend/src/pages/MeetingDetailPage/index.tsx
- frontend/src/styles/themes/theme.ts
Close #550 
feature/be/login -> dev
- 반응형 ui
- 10분 단위 선택
- 이벤트 추가버튼 제거
> [FE] 일정 생성 페이지 UI/UX 개선

- frontend/src/components/@shared/Avatar/index.tsx
- frontend/src/components/CoffeeStackItem/index.tsx
- frontend/src/components/MeetingItem/index.tsx
- frontend/src/components/layouts/Header/index.tsx
- frontend/src/pages/MeetingListPage/MeetingListPage.styled.ts
- frontend/src/pages/MeetingListPage/index.tsx
Close #565 
feature/fe/a11y -> dev
> [FE] 미팅 리스트 페이지 접근성 적용

- .github/workflows/frontend-ci.yml
Close #580 
feature/fe/remove-crendentials -> dev
- 프론트엔드 ci workflow에서 google api client id를 제거한다.
- 서브모듈을 업데이트한다.
- workflow yml에서 client id 제거 후 secret으로 참조
- 서브모듈 업데이트
> [ALL] Credential token 제거

- frontend/src/apis/userApis.ts
Close #584 
feature/fe/payload-bug-fix -> dev
- body를 포함하지 않는 POST 요청 시 `post` 메소드 사용 대신 instance에 config 객체를 인자로 전달
> [FE] POST 요청 시 payload null 포함되는 에러 수정
