woowacourse-teams/2022-moragora

backend/src/main/java/com/woowacourse/moragora/controller/ControllerAdvice.java
backend/src/main/java/com/woowacourse/moragora/controller/DiscussionController.java
backend/src/main/java/com/woowacourse/moragora/dto/DiscussionResponse.java
backend/src/main/java/com/woowacourse/moragora/entity/Discussion.java
backend/src/main/java/com/woowacourse/moragora/exception/DiscussionNotFoundException.java
backend/src/main/java/com/woowacourse/moragora/repository/DiscussionRepository.java
backend/src/main/java/com/woowacourse/moragora/service/DiscussionService.java
backend/src/test/java/com/woowacourse/moragora/acceptance/AcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/acceptance/DiscussionAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/controller/DiscussionControllerTest.java
backend/src/test/java/com/woowacourse/moragora/repository/DiscussionRepositoryTest.java
backend/src/test/java/com/woowacourse/moragora/service/DiscussionServiceTest.java
backend/src/test/resources/truncate.sql

Close #27 
feat/be/discussion-find-one -> develop
- 토론 게시글 단일 조회 시 상세 정보를 반환한다.
- 존재하지 않는 토론 게시글 조회 시 Not Found를 반환한다.
CustomException 계층에 대해 고민해보아요.

[BE] Discussion 단일 조회 기능 추가 및 테스트

---

backend/src/main/java/com/woowacourse/moragora/ApplicationStartupRunner.java
backend/src/main/java/com/woowacourse/moragora/dto/MeetingResponse.java
backend/src/main/java/com/woowacourse/moragora/dto/UserResponse.java
backend/src/main/java/com/woowacourse/moragora/entity/User.java
backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
backend/src/test/java/com/woowacourse/moragora/acceptance/MeetingAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/moragora/service/MeetingServiceTest.java

close #70 
feature/be/meeting-attendances-find-one -> dev
- Meeting 단일 조회시 해당 Meeting의 참석하는 User 들의 정보와 지각 횟수을 반환한다.
- User Entity의 email 필드 추가.
- git commit 내용이 아래와 같이 깨지는 현상이 있음
- 내용은 아래와 같음
feat: Meeting 단일 조회 기능 추가 구현

[BE] Meeting 단일 조회 기능 추가 구현

---

backend/src/main/java/com/woowacourse/auth/config/LoginArgumentResolver.java
backend/src/main/java/com/woowacourse/moragora/controller/MeetingController.java
backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java

Close #126 
feature/be/apply-argument-resolver -> dev
- controller parameter에 Argument Resolver를 적용한 후 Controller Test를 통과시킨다
- service mocking 시 argument로 null을 허용하여 test 깨지는 문제 해결
- argument mocking시, `any()` method에는 `@NotNull`이 적용되어 있어 null이 들어올 경우 mocking하지 않습니다. 따라서 null이 들어올 경우에도 mocking되길 원한다면 `nullable()` method를 사용해야 합니다.

[BE] Meeting Controller에 Argument Resolver 적용

---

backend/src/main/java/com/woowacourse/auth/config/LoginArgumentResolver.java
backend/src/main/java/com/woowacourse/auth/config/LoginInterceptor.java
backend/src/main/java/com/woowacourse/auth/config/WebConfig.java
backend/src/main/java/com/woowacourse/moragora/controller/ControllerAdvice.java
backend/src/main/java/com/woowacourse/moragora/controller/UserController.java
backend/src/main/java/com/woowacourse/moragora/dto/SearchedUserResponse.java
backend/src/main/java/com/woowacourse/moragora/dto/SearchedUsersResponse.java
backend/src/main/java/com/woowacourse/moragora/exception/NoKeywordException.java
backend/src/main/java/com/woowacourse/moragora/repository/UserRepository.java
backend/src/main/java/com/woowacourse/moragora/service/UserService.java
backend/src/test/java/com/woowacourse/moragora/acceptance/UserAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/moragora/controller/UserControllerTest.java
backend/src/test/java/com/woowacourse/moragora/repository/UserRepositoryTest.java
backend/src/test/java/com/woowacourse/moragora/service/UserServiceTest.java

ex) feature/be/auth-bean -> dev
수동 빈 등록에서 자동 빈 등록으로 변경한다.
`LoginInterceptor`와 `LoginArgumentResolver`를 @Component 어노테이션을 이용해 등록되도록 수정.

[BE] Interceptor 및 ArgumentResolver 등록 방식 변경

---

backend/src/test/java/com/woowacourse/auth/controller/AuthControllerTest.java
backend/src/test/java/com/woowacourse/moragora/controller/ControllerTest.java
backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/moragora/controller/UserControllerTest.java

Close #147 
feature/be/controllertest-structure -> dev
- 모든 ControllerTest 클래스가 실행할 때 스프링 컨테이너를 한 번만 띄우게 하기 위해 상위 클래스에서 환경 설정을 한다.
- mockMvc의 post, get, put 같은 메서드를 분리하여 코드의 반복을 줄인다.

[BE] Controller Test 동일한 환경을 위한 상위 클래스 분리 

---

frontend/src/components/UserItem/index.tsx
frontend/src/mocks/fixtures/users.ts
frontend/src/mocks/handlers/meetingHandler.ts
frontend/src/mocks/handlers/userHandler.ts
frontend/src/pages/MeetingPage/MeetingPage.styled.ts
frontend/src/pages/MeetingPage/index.tsx

Close #132 
feature/fe/user-attendance -> dev
- 체크박스 클릭시 서버로 데이터 변경 요청
- 출석 여부에 따른 체크박스 UI 변경
- 출석 체크 api mocking
- userItem 및 meeting page 기능 연결
- meetings mock handler에 출석 체크 api mocking
- 출석 마감 버튼 및 attendance form, modal 제거
- userItem에 체크박스 클릭 핸들러 추가
- 클릭시 핸들러 인자로 user정보, check상태 전달 
- checked에 따라 `present`, `tardy` 출석정보를 서버로 데이터 변경 요청
- 성공했을 경우 다시 데이터를 받아오기 위한 refetch
- 실패했을 경우 alert
Optimistic UI를 적용하려고 시도했지만 현재 상황이
```javascript
const meetingState = useFetch<MeetingResponseBody>(`/meetings/${id}`)
```
로 meeting의 데이터를 받아오고 있고, meeting 데이터를 상태로 가지기 위해 따로 fetch를 구현하기에는 
loading, error를 사용하지 않을 수는 없어서 출석 체크 요청 후 refetch하는 방법을 선택했어요.
react query 같은 경우에는 onMutataion을 옵션을 주고 fetch 함수가 실행되기 전에 실행하는 로직을 받도록 하는데 
이거랑 유사하게 useFetch에 옵션을 추가로 구현하거나, 나중에 query 훅을 만들면서 Optimistic을 적용하는게 어떨까 생각합니다 …

[FE] user attendance 체크 기능 추가

---

backend/src/main/java/com/woowacourse/moragora/dto/MyMeetingsResponse.java
backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/moragora/service/MeetingServiceTest.java

Close #170 
feature/be/servertime-formatting -> dev
- 로그인한 회원의 참가 미팅 목록 조회 시 서버시간 `Timestamp`로 응답

[BE] 서버시간 응답 형식 Timestamp로 수정

---

backend/src/main/java/com/woowacourse/ApplicationStartupRunner.java
backend/src/main/java/com/woowacourse/moragora/dto/MyMeetingResponse.java
backend/src/main/java/com/woowacourse/moragora/dto/MyMeetingsResponse.java
backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
backend/src/test/java/com/woowacourse/moragora/acceptance/MeetingAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/moragora/service/MeetingServiceTest.java

Close #172 
feature/be/mymeetingresponse-refactor -> dev
- User가 속한 각 미팅 정보를 넘겨줄 때, User 개인의 지각 스택을 함께 보내준다
- MMeetingResponse에 tardyCount 추가

[BE] 유저별 참여 모임 전체 조회 API 변경 반영

---

backend/src/main/java/com/woowacourse/moragora/entity/Status.java
backend/src/main/java/com/woowacourse/moragora/service/closingstrategy/RealTimeChecker.java

Close #192
feature/be/attendance-bug-fix -> dev
- 출결 체크 요청 시 status 정확하게 mapping
- 출결 마감 시간 연산 오류 수정
- Status enum 동등성 비교 시 case ignore
- 출결 마감 시간 기준을 서버시간 -> 모임 시작 시간으로 수정

[BE] 출결 체크 시 status mapping 및 마감 시간 오류 수정

---

frontend/src/components/MemberAddInput/index.tsx

Close #197 
feature/fe/member-include-user-bug -> dev
- 미팅 추가 페이지에서 멤버를 추가할 때 생성 유저가 포함되지 않음
- 검색된 멤버들인 `queryResult`에서 현재 유저를 필터링한다.

[FE] 멤버 검색에 현재 유저 포함되는 버그 해결

---

backend/src/main/java/com/woowacourse/auth/service/AuthService.java
backend/src/main/java/com/woowacourse/moragora/entity/user/EncodedPassword.java
backend/src/main/java/com/woowacourse/moragora/entity/user/User.java
backend/src/test/java/com/woowacourse/moragora/entity/user/UserTest.java

Close #208 
feature/be/login -> dev
- 패스워드 검증 책임 분리
- 기존 `EncodedPassword`에서 사용하던 `CryptoEncoder`를 제거하고 `RawPassword`를 받도록 수정

[BE] 패스워드 검증에 대한 책임 분리

---

frontend/src/consts/index.ts
frontend/src/contexts/queryClient.tsx
frontend/src/hooks/useMutation.ts
frontend/src/hooks/useQuery.ts
frontend/src/types/queryType.ts
frontend/src/types/useQueryType.ts

Close #223
feature/fe/async-fetch-hook -> dev
- 커스텀 훅 구현
- 컨텍스트 API 사용하여 캐시 데이터 컨텍스트 추가
- `const` 폴더에 `QUERY_STATUS`, `MUTATION_STATUS` 상수  추가
현재 타입을 분리한 파일인 `useQueryType.ts`의 네이밍이 `useMutation`을 포함하지 않는 것처럼 보여 이에 대한 논의가 필요합니다.

[FE] useQuery, useMutation 구현

---

backend/src/docs/asciidoc/common.asciidoc
backend/src/docs/asciidoc/index.asciidoc
backend/src/main/java/com/woowacourse/moragora/controller/CommonController.java
backend/src/main/java/com/woowacourse/moragora/dto/MyMeetingsResponse.java
backend/src/main/java/com/woowacourse/moragora/dto/ServerTimeResponse.java
backend/src/main/java/com/woowacourse/moragora/service/CommonService.java
backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
backend/src/test/java/com/woowacourse/moragora/acceptance/CommonAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/controller/CommonControllerTest.java
backend/src/test/java/com/woowacourse/moragora/controller/ControllerTest.java
backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/moragora/service/CommonServiceTest.java
backend/src/test/java/com/woowacourse/moragora/service/MeetingServiceTest.java

Close #232 
feature/be/show-server-time -> dev
- 자신의 미팅 목록 조회에 포함되어 있던 서버 시간 응답을 별도 api로 분리
- `CommonService.getServerTime()`의 로직이 너무 단순하고 서버 환경 의존적이어서 test 로직 짜기가 애매하네요... 일단은 test를 위한 test로 만들었습니다 😢

[BE] 현재 서버 시간 요청 api 분리

---

backend/src/main/java/com/woowacourse/ApplicationStartupRunner.java
backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
backend/src/main/java/com/woowacourse/moragora/dto/MeetingResponse.java
backend/src/main/java/com/woowacourse/moragora/dto/MyMeetingResponse.java
backend/src/main/java/com/woowacourse/moragora/entity/Attendance.java
backend/src/main/java/com/woowacourse/moragora/entity/MeetingAttendances.java
backend/src/main/java/com/woowacourse/moragora/entity/ParticipantAttendances.java
backend/src/main/java/com/woowacourse/moragora/exception/InvalidCoffeeTimeException.java
backend/src/main/java/com/woowacourse/moragora/service/AttendanceService.java
backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
backend/src/test/java/com/woowacourse/moragora/acceptance/AcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/acceptance/AttendanceAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/controller/AttendanceControllerTest.java
backend/src/test/java/com/woowacourse/moragora/controller/ControllerTest.java
backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/moragora/entity/MeetingAttendancesTest.java
backend/src/test/java/com/woowacourse/moragora/service/AttendanceServiceTest.java
backend/src/test/java/com/woowacourse/moragora/service/MeetingServiceTest.java

Close #210 
feature/be/coffee-stack-use -> dev
- 커피 스택 비우기 기능 구현
- 커피 스택 비우기 기능 구현
- 전체 미팅 리스트 조회에 `isCoffeeTime` 필드 추가
- 단일 미팅 조회에 `isCoffeeTime` 필드 추가
- `Attendance`에 `disabled` 필드 추가

[BE] 커피스택 비우기 기능 구현

---

backend/src/docs/asciidoc/meeting.asciidoc
backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
backend/src/main/java/com/woowacourse/moragora/dto/CoffeeStatResponse.java
backend/src/main/java/com/woowacourse/moragora/dto/CoffeeStatsResponse.java
backend/src/main/java/com/woowacourse/moragora/entity/Attendance.java
backend/src/main/java/com/woowacourse/moragora/entity/Meeting.java
backend/src/main/java/com/woowacourse/moragora/entity/MeetingAttendances.java
backend/src/main/java/com/woowacourse/moragora/entity/user/User.java
backend/src/main/java/com/woowacourse/moragora/service/AttendanceService.java
backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
backend/src/test/java/com/woowacourse/moragora/acceptance/AttendanceAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/controller/AttendanceControllerTest.java
backend/src/test/java/com/woowacourse/moragora/entity/MeetingAttendancesTest.java
backend/src/test/java/com/woowacourse/moragora/service/AttendanceServiceTest.java

Close #246 
feature/be/show-coffee-use -> dev
- 커피 비우기 전 소비할 내역 조회
- 누가 커피를 몇 잔 사야하는지 반환
- 커피 스택을 비울 때 비울 개수를 parameter로 받지 않고 내부 필드 `numberOfParticipants`로 결정합니다

[BE] 커피 비우기 전 소비할 내역 조회하기 기능

---

backend/src/main/java/com/woowacourse/moragora/service/EventService.java

Close #270 
feature/be/scheduling -> dev
- 스케줄링이 모임 시작 1 분전에 생성되는 것으로 변경한다.

[BE] 출석부 생성 시간 입장 시간 1분 전으로 변경

---

backend/src/docs/asciidoc/attendance.asciidoc
backend/src/docs/asciidoc/index.asciidoc
backend/src/main/java/com/woowacourse/moragora/controller/AttendanceController.java
backend/src/main/java/com/woowacourse/moragora/controller/EventController.java
backend/src/main/java/com/woowacourse/moragora/dto/AttendanceResponse.java
backend/src/main/java/com/woowacourse/moragora/dto/AttendancesResponse.java
backend/src/main/java/com/woowacourse/moragora/dto/ParticipantResponse.java
backend/src/main/java/com/woowacourse/moragora/entity/Status.java
backend/src/main/java/com/woowacourse/moragora/service/AttendanceService.java
backend/src/main/java/com/woowacourse/moragora/service/EventService.java
backend/src/test/java/com/woowacourse/moragora/acceptance/AttendanceAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/controller/AttendanceControllerTest.java
backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/moragora/service/AttendanceServiceTest.java
backend/src/test/java/com/woowacourse/moragora/service/MeetingServiceTest.java
backend/src/test/java/com/woowacourse/moragora/support/EventFixtures.java

Close #292 
feature/be/attendance-find-all -> dev
- 오늘 날짜의 출석부만 조회할 수 있도록 구현
- 출석부 조회 기능 Test 추가
- 출석 생성 로직 변경 (Scheduling 제거)
- 출석부 생성 방식이 변경됨
기존에 스케줄링으로 출석부를 생성했는데, 우선 모든 이벤트에 대한 출석을 NONE으로 저장하도록 변경.
- 스케줄링을 아직 지우지 않은 이유는 TARDY로 자동적으로 변경시키도록 하기 위함.
1. 변경된 출석부 생성 방식
2. 출석부는 모두가 볼 수 있는지
3. 출석부를 조회할 수 있는 시간대
4. AttendanceServiceTest에서 ID 검증 방법? (아래 코드 comment 확인)

[BE] 출석부 조회 기능 구현

---

backend/src/docs/asciidoc/event.asciidoc
backend/src/docs/asciidoc/index.asciidoc
backend/src/main/java/com/woowacourse/moragora/controller/EventController.java
backend/src/main/java/com/woowacourse/moragora/dto/EventRequest.java
backend/src/main/java/com/woowacourse/moragora/dto/EventResponse.java
backend/src/main/java/com/woowacourse/moragora/dto/MyMeetingResponse.java
backend/src/main/java/com/woowacourse/moragora/entity/Event.java
backend/src/main/java/com/woowacourse/moragora/service/AttendanceService.java
backend/src/main/java/com/woowacourse/moragora/service/EventService.java
backend/src/main/java/com/woowacourse/moragora/service/MeetingService.java
backend/src/main/java/com/woowacourse/moragora/support/ServerTimeManager.java
backend/src/test/java/com/woowacourse/moragora/acceptance/AcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/acceptance/AttendanceAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/acceptance/EventAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/acceptance/MeetingAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/controller/EventControllerTest.java
backend/src/test/java/com/woowacourse/moragora/controller/MeetingControllerTest.java
backend/src/test/java/com/woowacourse/moragora/repository/EventRepositoryTest.java
backend/src/test/java/com/woowacourse/moragora/service/AttendanceServiceTest.java
backend/src/test/java/com/woowacourse/moragora/service/EventServiceTest.java
backend/src/test/java/com/woowacourse/moragora/service/MeetingServiceTest.java
backend/src/test/java/com/woowacourse/moragora/support/EventFixtures.java

Close #294 
Close #304 
feature/be/show-upcoming-event -> dev
- 모임에 설정된 이벤트 중 가장 가까운 날짜의 이벤트 조회 구현
- 모임 목록 조회 필드 수정 및 가까운 일정 정보 필드 추가
- 테스트 코드 작성
response Dto 필드들을 renaming하면서 Event Entity 필드도 rename할까 했으나
- Entity 필드도 rename 해야할 지
- 한다면 DB 필드명도 함께 따라가는지
- 한다면 `meetingStartTime`, `meetingEndTime`으로 하는지 아니면 `startTime`, `endTime`으로 하는지
등 추가적인 논의가 필요할 것 같아 일단은 Dto만 renaming 했습니다!

[BE] 가장 가까운 이벤트 단일 조회 구현, 미팅 목록 조회 API 수정

---

frontend/.storybook/preview.js

Close #352 
feature/fe/remove-storybook-padding -> dev
- 스토리북 `preview.js`에 `layout` 파라미터를 `fullscreen`으로 설정

[FE] 스토리북 preview padding 제거

---

frontend/cypress/e2e/app.cy.ts
frontend/src/apis/meetingApis.ts
frontend/src/components/CoffeeStackModal/CoffeeStackModal.styled.ts
frontend/src/mocks/fixtures/meetings.ts
frontend/src/mocks/handlers/meetingHandler.ts
frontend/src/pages/CalendarPage/index.tsx
frontend/src/pages/CoffeeStackPage/index.tsx
frontend/src/pages/MeetingConfigPage/MasterAssignSection/MasterAssignSection.stories.jsx
frontend/src/pages/MeetingConfigPage/MasterAssignSection/MasterAssignSection.styled.ts
frontend/src/pages/MeetingConfigPage/MasterAssignSection/index.tsx
frontend/src/pages/MeetingConfigPage/MeetingConfigPage.styled.ts
frontend/src/pages/MeetingConfigPage/index.tsx
frontend/src/pages/MeetingCreatePage/index.tsx
frontend/src/pages/MeetingDetailPage/MeetingDetailPage.styled.ts
frontend/src/router/index.tsx
frontend/src/types/meetingType.ts

Close #312 
feature/fe/meeting-config-page -> dev
- MeetingConfigPage 추가

[FE] 모임 페이지 하위에 마스터 및 일반 참가자 모임 설정 페이지 구현

---

.github/workflows/sonarqube.yml

Close #386 
fix/be/sonarqube-with-submodule -> dev
소나큐브 workflow에서 서브모듈 토큰을 못 읽는 문제를 해결한다.

[BE] 소나큐브 서브모듈토큰 에러 

---

frontend/package-lock.json
frontend/package.json
frontend/webpack/webpack.prod.js

Close #413 
feature/fe/performance-optimization -> dev
- production 모드의 웹팩 소스맵 방식을 변경한다.
- [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer)를 설치한다.
- production 모드에서만 번들 사이즈를 측정한다.
- `analyzerMode`를 `disabled`로 설정하고 `generateStatsFile`을 `true`로 해 json 파일을 출력한다.
- `reportFilename`을 `stats/stats-${currentDate}.json`로 설정한다.
- `currentDate`는 읽기의 편의를 위해 ISO 8601 포맷에서 밀리세컨드를 제거한다.
```bash
npx webpack-bundle-analyzer <bundleStatsFile> build/ --port 8888
```
설정 전  | 설정 후 
---|---
1.61 MB | 311.09 KB
약 80% 감소

[FE] production 모드의 웹팩 소스맵 방식 변경

---

frontend/cypress.config.ts
frontend/src/router/Auth.tsx

Close #417 
feature/fe/fix-auth -> dev
로그인한 상태에서 url을 주소창에 입력하여 접속 시 해당 페이지가 보여진다.
- https://github.com/woowacourse-teams/2022-moragora/issues/417#issuecomment-1247605342
- 불필요한 `console.log 제거`

[FE] Auth 시 메인 페이지로 리다이렉션되는 버그 수정

---

backend/src/main/java/com/woowacourse/moragora/entity/Attendance.java
backend/src/main/java/com/woowacourse/moragora/entity/Meeting.java
backend/src/test/java/com/woowacourse/moragora/entity/AttendanceTest.java
backend/src/test/java/com/woowacourse/moragora/entity/EventTest.java
backend/src/test/java/com/woowacourse/moragora/entity/MeetingAttendancesTest.java
backend/src/test/java/com/woowacourse/moragora/entity/ParticipantAttendancesTest.java
backend/src/test/java/com/woowacourse/moragora/entity/ParticipantTest.java

Close #424 
feature/be/entity-test -> dev
- 누락된 단위 테스트를 추가했습니다.
- equals&hashcode를 @Lombok을 이용해서 정의하는 방법을 변경하였습니다.
기존에 ide에서 만든 equals hashcode 메서드는 jacoco에서 커버리지를 측정하기 때문에, 커버리지 기준에 못 미칠수도 있습니다. 
현재 lombok에서 제공하는 메서드들은 jacoco에서 제외가 되기 때문에 equals hashcode 정의 방법을 변경하는 것에 대해 어떻게 생각하신가요?

[BE] 누락된 엔티티 단위 테스트 추가

---

frontend/src/components/CoffeeStackModal/index.tsx
frontend/src/pages/CheckInPage/index.tsx
frontend/src/pages/MeetingDetailPage/index.tsx
frontend/src/pages/MeetingListPage/index.tsx

Close #426 
feature/fe/fix-appear-error -> dev
- 각 페이지 로드 시 서버에서 데이터를 성공적으로 불러왔을 때 에러 컴포넌트가 나타나지 않는다.
- 모임 목록 페이지
- 모임 상세 페이지
- 커피 스택 비우기 모달창
- 출석 페이지
- response body가 `undefined`인지 검사하는 조건 제거
- response body에 대한 optional 연산자 추가

[FE] 페이지에서 데이터를 불러왔을 때 에러 컴포넌트가 잠시 나타나는 버그 수정

---

backend/build.gradle
backend/lombok.config

feature/be/jacoco -> dev
- jacoco를 이용해서 최소 테스트 커버리지 기준을 설정했습니다.
현재로서는 80%를 기준으로 설정을 해놓았는데 엔티티 클래스들이 80%를 넘기지 못하고 있어요.. equals & hashCode 같은 메서드 때문에요! 
새로 추가한 lombok.config에 적용한 설정을 해놓으면 롬복으로 만든 메서드들 (@getter, @builder) 은 jacoco 커버리지에서 제외되게 되는데요! equals & hashcode들을 롬복으로 적용하는 것은 어떻게 생각하신지? 아니면 커버리지 기준을 조금 낮춰도 될것같아요!

[BE] jacoco 테스트 커버리지 기준 설정

---

frontend/webpack/webpack.common.js

Close #432 
feature/fe/output-filename-hash -> dev
- webpack output filename에 content-hash 추가
- output.filename에 [contenthash]를 추가한다.
- output.assetModuleFilename의 [hash]를 [contenthash]로 변경한다.
```javascript
module.exports = {
...,
output: {
...,
filename: '[name].bundle.js',
assetModuleFilename: 'images/[hash][ext][query]',
...
},
```
```javascript
module.exports = {
...,
output: {
...,
filename: '[name].[contenthash].js',
assetModuleFilename: 'images/[hash][ext][query]',
...
},
```
- webpack output.filename을 contenthash로 설정함으로써 변경되지 않은 파일에 대해서는 filename을 변경하지않고 그에 따라서 busting하지 않기 때문에 caching을 유지하도록 한다. 
- hash나 contenthash template string 영향을 받지 않으므로 webpack docs를 따라서 hash로 설정한다.

[FE] webpack output filename에 hash 추가를 통한 Cache Busting

---

backend/src/main/java/com/woowacourse/moragora/application/UserService.java
backend/src/main/java/com/woowacourse/moragora/application/auth/AuthService.java
backend/src/main/java/com/woowacourse/moragora/domain/user/User.java
backend/src/main/java/com/woowacourse/moragora/domain/user/UserRepository.java
backend/src/test/java/com/woowacourse/moragora/application/UserServiceTest.java
backend/src/test/java/com/woowacourse/moragora/domain/user/UserRepositoryTest.java
backend/src/test/java/com/woowacourse/moragora/domain/user/UserTest.java
backend/src/test/java/com/woowacourse/moragora/support/fixture/UserFixtures.java

Close #452 #420 
feature/be/register -> dev
- 회원가입 시 같은 이메일과 provider로 이미 존재하는지 검증한다.
- User의 email unique 제약을 제거한다.

[BE] 유저 이메일 unique 제약 제거 및 회원가입 시 중복 검사 기능 추가

---

backend/src/main/java/com/woowacourse/moragora/dto/response/user/UserResponse.java
backend/src/test/java/com/woowacourse/moragora/acceptance/UserAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/application/UserServiceTest.java
backend/src/test/java/com/woowacourse/moragora/application/auth/AuthServiceTest.java
backend/src/test/java/com/woowacourse/moragora/presentation/UserControllerTest.java

Close #458 
feature/be/user-find-refactor -> dev
- User 정보 응답 시 회원가입 기관 정보 추가
- UserResponse에 authProvider 추가
-

[BE] User 정보 응답 시 회원가입 기관 정보 추가

---

frontend/src/contexts/userContext.tsx
frontend/src/mocks/fixtures/users.ts
frontend/src/mocks/handlers/userHandler.ts
frontend/src/pages/UserConfigPage/index.tsx
frontend/src/types/userType.ts

Close #456 
feature/fe/oauth-userconfig-change -> dev
- 비밀번호 변경 페이지 접근을 제한한다.
- UserConfigPage의 비밀번호 변경 메뉴를 비활성화 한다.
- 회원 탈퇴 서명만 받고, 비밀번호는 받지 않는다.
mockgin 수정
- user 데이터에 authProvider 추가
- login/oauth에 targetUser를 user2로 변경 및 authProvider ‘google’로 변경
- new User 수정
- users/me 응답에 authProvider 추가
타입 수정
- userContext에 UserContextData 타입 수정
- User 타입 수정
- Participant 타입 수정
- GetLoginUserDataResponseBody 타입 수정
도메인 수정
- UserConfigPage 비밀 번호 변경 및 회원 탈퇴 메뉴 비활성화
- OAuth 로그인 유저 회원 탈퇴를 위해서 비밀번호를 받지 않는 새로운 api구현
- 비밀번호를 받지 않고 바로 탈퇴를 하게 되면 타인이 쉽게 탈퇴를 시켜버릴 수 있다
-> 탈퇴 전에 모달로 한번더 확인하는 것으로 합의
- Google 계정으로 부여된 로그인 권한을 delete 시켜야 한다.
-> 서버에서 현재 accessToken 및 refreshToken을 저장하지 않고 있고, 권한을 취속하기 위해서 accessToken 재요청 및 refreshToken 저장방식을 고민해봐야하는 이유가 있기 때문에 다음 스프린트에서 시간을 잡고 구현한다.
>이런한 이유로 현재 OAuth 로그인 유저일 경우에 …

[FE] OAuth 로그인 유저 비밀번호 수정, 회원 탈퇴 방식 변경

---

backend/src/main/java/com/woowacourse/moragora/application/EventService.java
backend/src/main/java/com/woowacourse/moragora/application/ServerTimeManager.java
backend/src/main/java/com/woowacourse/moragora/support/timestrategy/DateTime.java
backend/src/test/java/com/woowacourse/moragora/acceptance/AttendanceAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/application/EventServiceTest.java

#477 
feature/be/event-create -> dev
현재 시간 이후로 일정을 생성할 수 있도록 변경한다.
- 기존에 출석시간 이후로 일정을 생성할 수 있도록 되어있었는데,현재 시간 이후로 일정을 생성하도록 변경한다.

[BE] 출석 시간 전이 아닌 현재시간 이전의 이벤트 생성을 못하도록 변경

---

backend/src/main/java/com/woowacourse/moragora/presentation/auth/LoginInterceptor.java

Close #486 
hotfix/1.1.2 -> main
만료된 토큰에 대한 응답을 500에서 401로 수정한다
Class Annotation 검사 시 `getBean().getClass()`하면 프록시 관련 객체 class가 반환됨
`getBeanType()`으로 해야 Controller Class 반환

[BE] LoginInterceptor annotation 검사 로직 오류 수정 및 hotfix

---

backend/src/main/java/com/woowacourse/moragora/application/MeetingService.java
backend/src/main/java/com/woowacourse/moragora/domain/exception/BusinessException.java
backend/src/main/java/com/woowacourse/moragora/domain/meeting/Meeting.java
backend/src/main/java/com/woowacourse/moragora/domain/meeting/MeetingRepository.java
backend/src/main/java/com/woowacourse/moragora/domain/participant/Participant.java
backend/src/main/java/com/woowacourse/moragora/domain/participant/ParticipantAndCount.java
backend/src/main/java/com/woowacourse/moragora/domain/query/QueryRepository.java
backend/src/main/java/com/woowacourse/moragora/domain/user/User.java
backend/src/main/java/com/woowacourse/moragora/domain/user/UserRepository.java
backend/src/main/java/com/woowacourse/moragora/dto/response/meeting/MeetingResponse.java
backend/src/main/java/com/woowacourse/moragora/dto/response/meeting/ParticipantResponse.java
backend/src/test/java/com/woowacourse/moragora/acceptance/MeetingAcceptanceTest.java
backend/src/test/java/com/woowacourse/moragora/application/MeetingServiceTest.java
backend/src/test/java/com/woowacourse/moragora/domain/meeting/MeetingRepositoryTest.java
backend/src/test/java/com/woowacourse/moragora/domain/meeting/MeetingTest.java
backend/src/test/java/com/woowacourse/moragora/domain/participant/ParticipantTest.java
backend/src/test/java/com/woowacourse/moragora/domain/query/QueryRepositoryTest.java
backend/src/test/java/com/woowacourse/moragora/domain/user/UserTest.java
backend/src/test/java/com/woowacourse/moragora/presentation/MeetingControllerTest.java

Close #500
feature/be/meeting-findbyid -> dev
- isActive 필드 제거
- 코드 리팩토링
- 테스트 코드 추가 및 수정
- JPA 최적화 - 14개 -> 3개의 쿼리로 리팩토링
- 불필요한 fIndBy 보다 Exists로 존재여부 확인하도록 수정

[BE] 미팅 조회에서의 findById 최적화

---

frontend/emotion.d.ts
frontend/src/App.styled.ts
frontend/src/App.tsx
frontend/src/components/@shared/Calendar/DateCell/DateCell.styled.ts
frontend/src/components/@shared/ModalWindow/ModalWindow.styled.ts
frontend/src/components/CoffeeStackModal/CoffeeStackModal.styled.ts
frontend/src/components/MemberAddInput/MemberAddInput.styled.ts
frontend/src/components/ModalPortal/ModalPortal.styled.ts
frontend/src/components/layouts/AppLayout/AppLayout.styled.ts
frontend/src/components/layouts/AppLayout/index.tsx
frontend/src/components/layouts/Body/Body.styled.ts
frontend/src/components/layouts/Footer/Footer.styled.ts
frontend/src/components/layouts/Header/Header.styled.ts
frontend/src/pages/CoffeeStackPage/CoffeeStackPage.styled.ts
frontend/src/pages/MeetingConfigPage/MasterAssignSection/MasterAssignSection.styled.ts
frontend/src/pages/MeetingDetailPage/MeetingDetailPage.styled.ts
frontend/src/pages/MeetingListPage/MeetingListPage.styled.ts
frontend/src/styles/GlobalStyles/index.tsx
frontend/src/styles/themes/theme.ts
frontend/src/utils/debounce.ts

Close #499 
hotfix/1.1.4 -> main
- 모바일 환경에서 상단, 하단 네비게이션 바가 정상적으로 나타난다.
- `Header`, `Footer` layout 조정을 inset에서 height 지정으로 변경
- `AppLayout` Height 적용
- 주소창을 제외한 레이아웃 뷰포트 높이를 나타내는 `window.innerHeight`를 사용해서 높이 지정
- `App` 로딩 스피너 `Box` 추가

[FE] Mobile 상단, 하단 navigation Layout 버그 수정

---

frontend/cypress/e2e/app.cy.ts
frontend/src/apis/userApis.ts
frontend/src/components/EmailConfirmModal/EmailConfirmModal.stories.jsx
frontend/src/components/EmailConfirmModal/EmailConfirmModal.styled.ts
frontend/src/components/EmailConfirmModal/index.tsx
frontend/src/mocks/handlers/userHandler.ts
frontend/src/pages/RegisterPage/index.tsx
frontend/src/types/userType.ts
frontend/src/utils/timeUtil.ts

Close #521 
feature/fe/verify-email -> dev
- 중복확인에서 인증하기 버튼으로 변경
- 이메일 인증코드 입력 모달 추가
- 인증 만료까지 남은 시간을 보여준다.
- 인증이 완료되었지 않으면 인증하기 버튼 활성화 및 상태 저장
- 시간 만료되면 입력 막고 “인증 시간이 만료되었습니다” placeholder로 보여준다.
- 숫자 이외에 입력을 막고, 최대 입력값을 6자리로 제한한다. 
- 재전송했을 때 시간 달라짐
- 스토리북 추가
- 회원가입, 모임 생성 E2E 테스트 코드 수정
- 이메일 전성, 인증 코드 확인 mocking 추가

[FE] 회원가입 시 이메일 인증 기능 추가

---

backend/src/main/java/com/woowacourse/moragora/application/UserService.java
backend/src/main/java/com/woowacourse/moragora/application/auth/AuthService.java
backend/src/main/java/com/woowacourse/moragora/domain/user/UserRepository.java
backend/src/test/java/com/woowacourse/moragora/application/UserServiceTest.java
backend/src/test/java/com/woowacourse/moragora/application/auth/AuthServiceTest.java

Close #524 
feature/be/email-integration -> dev
- google oauth 로그인 시 이미 가입된 이메일은 기존의 유저 데이터로 로그인한다.
- AuthService의 loginWithGoogle 메서드에서 이메일을 조회할 때 provider와 함께 조회하지 않고 이메일만 조회를 한다.

[BE] Oauth 로그인 시 이미 가입된 이메일인 경우 해당 유저 데이터로 로그인

---

backend/src/main/java/com/woowacourse/moragora/application/UserService.java
backend/src/main/java/com/woowacourse/moragora/application/auth/AuthService.java
backend/src/test/java/com/woowacourse/moragora/application/auth/AuthServiceTest.java

Close #559 
feature/be/refresh -> dev
- Token 재발행시 DB로부터 유저가 존재하는지 검증하는 로직을 제거한다.

[BE] Token 재발행시 유저 검증 로직 제거

---

frontend/src/App.tsx

Close #586 
feature/fe/refresh-bug-fix -> dev
- 기존에 withCredential없이 요청이 들어가던 refresh api 수정

[ALL] Refresh Token 관리 문제
